/**
 * Terms of Service — standard construction business terms.
 */
import {
  SiteNav,
  SiteFooter,
  MobileCTABar,
} from "@/components/layout/SiteShell";
import { SITE } from "@/const";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      <SiteNav />
      <MobileCTABar />

      <main className="flex-1 pt-28 pb-20">
        <div className="container max-w-3xl">
          <span
            className="block text-[10px] tracking-[0.3em] uppercase text-primary font-bold mb-3"
            style={{ fontFamily: "var(--font-condensed)" }}
          >
            Legal
          </span>
          <h1
            className="text-3xl sm:text-4xl font-semibold mb-2"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground mb-10">
            Last updated: April 2026
          </p>

          <div className="prose-custom space-y-8 text-sm text-muted-foreground leading-relaxed">
            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing and using the {SITE.name} website and client
                portal, you agree to be bound by these Terms of Service. If you
                do not agree to these terms, please do not use our services.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                2. Services
              </h2>
              <p>
                {SITE.name} ({SITE.license}) provides residential and commercial
                construction services in the Eugene, Oregon and Lane County
                area. Our website offers:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Project information and service descriptions</li>
                <li>
                  AI-powered project cost estimates (for informational purposes
                  only)
                </li>
                <li>Client portal access for active project management</li>
                <li>Contact and inquiry submission forms</li>
              </ul>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                3. Estimates and Pricing
              </h2>
              <p>
                All estimates provided through our website, including those
                generated by our AI Project Estimator, are for informational
                purposes only and do not constitute a binding offer or contract.
                Actual project costs may vary based on site conditions, material
                prices, scope changes, and other factors. A formal written
                contract will be provided before any work begins.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                4. Client Portal
              </h2>
              <p>
                Access to the client portal is provided to active clients of{" "}
                {SITE.name}. You are responsible for maintaining the
                confidentiality of your login credentials. Portal features
                including field reports, schedule views, finish selections, and
                budget tracking are provided for your convenience and
                informational purposes.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                5. Intellectual Property
              </h2>
              <p>
                All content on this website, including text, images, logos,
                design elements, and software, is the property of {SITE.name} or
                its licensors and is protected by copyright and other
                intellectual property laws.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                6. Limitation of Liability
              </h2>
              <p>
                {SITE.name} provides this website and its content on an "as is"
                basis. We make no warranties regarding the accuracy,
                completeness, or reliability of any information on this site.
                Construction services are governed by separate written contracts
                between {SITE.name} and the client.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                7. Oregon Law
              </h2>
              <p>
                These terms are governed by the laws of the State of Oregon.{" "}
                {SITE.name} is licensed under Oregon Construction Contractors
                Board license {SITE.license}.
              </p>
            </section>

            <section>
              <h2
                className="text-lg font-semibold text-foreground mb-3"
                style={{ fontFamily: "var(--font-heading)" }}
              >
                8. Contact
              </h2>
              <p>For questions about these terms, contact us:</p>
              <p className="mt-2">
                {SITE.name}
                <br />
                {SITE.location}
                <br />
                <a
                  href={SITE.emailHref}
                  className="text-primary hover:underline"
                >
                  {SITE.email}
                </a>
                <br />
                <a
                  href={SITE.phoneHref}
                  className="text-primary hover:underline"
                >
                  {SITE.phone}
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
